# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a5afd88bd7015f2de84363eea4fa80c178a8a701be513e07aafd569face74a02856aad6551568f3c1c2a083453d4e577279578db22d5e913f00a32c5295a2155

test:
  secret_key_base: 945893a138ea48549885d97baced24d76921650ca0a572957778c9ec7c4e7a2c97ddd814bfedd0098c53ef2a915242552ff5d60193f4badf829a2598a079314f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
